include /home/s/share/topmk/topmk.def

TARGETS = liblddnet.so

# Target specific variables
liblddnet.so_HEADERS = $(wildcard *.h)
liblddnet.so_HPREFIX = ldd/net
liblddnet.so_SOURCES = $(wildcard *.cc) $(wildcard internal/*.cc internal/*.c)
liblddnet.so_CXXFLAGS= -I../../  
liblddnet.so_LDFLAGS = -L../util 
liblddnet.so_LDLIBS  = -llddutil -levent
liblddnet.so_RPATHS  = ../util

# Variables affecting global compiler flags
DEBUGING = -g -DDEBUG # Comment this line for non-debugging code
OPTIMIZE = -O0 # Comment this line for optimized(-O3) code
WARNINGS+= -Werror # Comment this line if warning is a problem

# Packaging options
SRCTOP = 
SRCTAR = yes # Comment this line if no src tarball is needed

# Optional local files to be removed when making 'clean'
# Objects and libraries are taken care of, they do *not* need to be set here
CLEAN = 

# If this is a directory with subdirectories to build, set SUBDIRS
SUBDIRS = 

# Do not add any build rules until *after* the include of topmk.all
include /home/s/share/topmk/topmk.all
# Do not place any rules or targets above this line

