#!/bin/bash

name=example1

pwd=$(readlink -f $(dirname $0))
ln -sf ../../../lddskel $name
./$name \
    --cfg-dir=$pwd/../cfg \
    --pid-dir=$pwd/ \
    --lib-dir=$pwd/ \
    --log-dir=$pwd/log \
    --log-flush=1 \
    $@
rm -f $name
