# If this is a directory with subdirectories to build, set SUBDIRS
SUBDIRS = client example1 example2 template

# Do not add any build rules until *after* the include of topmk.all
include /home/s/share/topmk/topmk.all
# Do not place any rules or targets above this line

